$(document).ready(function(){
	$(".interest1").on("click",function(){
		$(this).css("background-color","tomato");
	});
	$(".interest1").click(function(){
		$(this).off("click");
	})
	$(".interest2").on("click",function(){
		$(this).css("background-color","tomato");
	});
	$(".interest2").click(function(){
		$(this).off("click");
	})
	$(".interest3").on("click",function(){
		$(this).css("background-color","tomato");
	});
	$(".interest3").click(function(){
		$(this).off("click");
	})
	$(".interest4").on("click",function(){
		$(this).css("background-color","tomato");
	});
	$(".interest4").click(function(){
		$(this).off("click");
	})
	$(".interest5").on("click",function(){
		$(this).css("background-color","tomato");
	});
	$(".interest5").click(function(){
		$(this).off("click");
	})
	$(".interest6").on("click",function(){
		$(this).css("background-color","tomato");
	});
	$(".interest6").click(function(){
		$(this).off("click");
	})
	$(".interest7").on("click",function(){
		$(this).css("background-color","tomato");
	});
	$(".interest7").click(function(){
		$(this).off("click");
	})
	$(".interest8").on("click",function(){
		$(this).css("background-color","tomato");
	});
	$(".interest8").click(function(){
		$(this).off("click");
	})
	$(".interest9").on("click",function(){
		$(this).css("background-color","tomato");
	});
	$(".interest9").click(function(){
		$(this).off("click");
	})
	$(".interest10").on("click",function(){
		$(this).css("background-color","tomato");
	});
	$(".interest10").click(function(){
		$(this).off("click");
	})
	$(".interest11").on("click",function(){
		$(this).css("background-color","tomato");
	});
	$(".interest11").click(function(){
		$(this).off("click");
	})
	$(".interest12").on("click",function(){
		$(this).css("background-color","tomato");
	});
	$(".interest12").click(function(){
		$(this).off("click");
	})
	$(".interest13").on("click",function(){
		$(this).css("background-color","tomato");
	});
	$(".interest13").click(function(){
		$(this).off("click");
	})
	$(".interest14").on("click",function(){
		$(this).css("background-color","tomato");
	});
	$(".interest14").click(function(){
		$(this).off("click");
	})
	$(".interest15").on("click",function(){
		$(this).css("background-color","tomato");
	});
	$(".interest15").click(function(){
		$(this).off("click");
	})
	$(".interest16").on("click",function(){
		$(this).css("background-color","tomato");
	});
	$(".interest16").click(function(){
		$(this).off("click");
	})
	$(".interest17").on("click",function(){
		$(this).css("background-color","tomato");
	});
	$(".interest17").click(function(){
		$(this).off("click");
	})
	$(".interest18").on("click",function(){
		$(this).css("background-color","tomato");
	});
	$(".interest18").click(function(){
		$(this).off("click");
	})
	$(".interest19").on("click",function(){
		$(this).css("background-color","tomato");
	});
	$(".interest19").click(function(){
		$(this).off("click");
	})
	$(".interest20").on("click",function(){
		$(this).css("background-color","tomato");
	});
	$(".interest20").click(function(){
		$(this).off("click");
	})
	$(".interest21").on("click",function(){
		$(this).css("background-color","tomato");
	});
	$(".interest21").click(function(){
		$(this).off("click");
	})
	$(".interest22").on("click",function(){
		$(this).css("background-color","tomato");
	});
	$(".interest22").click(function(){
		$(this).off("click");
	})
	$(".interest23").on("click",function(){
		$(this).css("background-color","tomato");
	});
	$(".interest23").click(function(){
		$(this).off("click");
	})
	$(".interest24").on("click",function(){
		$(this).css("background-color","tomato");
	});
	$(".interest24").click(function(){
		$(this).off("click");
	})
	$(".interest25").on("click",function(){
		$(this).css("background-color","tomato");
	});
	$(".interest25").click(function(){
		$(this).off("click");
	})
	$(".interest26").on("click",function(){
		$(this).css("background-color","tomato");
	});
	$(".interest26").click(function(){
		$(this).off("click");
	})
	$(".interest27").on("click",function(){
		$(this).css("background-color","tomato");
	});
	$(".interest27").click(function(){
		$(this).off("click");
	})
	$(".interest28").on("click",function(){
		$(this).css("background-color","tomato");
	});
	$(".interest28").click(function(){
		$(this).off("click");
	})
	$(".interest29").on("click",function(){
		$(this).css("background-color","tomato");
	});
	$(".interest29").click(function(){
		$(this).off("click");
	})
	$(".interest30").on("click",function(){
		$(this).css("background-color","tomato");
	});
	$(".interest30").click(function(){
		$(this).off("click");
	})
	$(".interest31").on("click",function(){
		$(this).css("background-color","tomato");
	});
	$(".interest31").click(function(){
		$(this).off("click");
	})
	$(".interest32").on("click",function(){
		$(this).css("background-color","tomato");
	});
	$(".interest32").click(function(){
		$(this).off("click");
	})
	$(".interest33").on("click",function(){
		$(this).css("background-color","tomato");
	});
	$(".interest33").click(function(){
		$(this).off("click");
	})
	$(".interest34").on("click",function(){
		$(this).css("background-color","tomato");
	});
	$(".interest34").click(function(){
		$(this).off("click");
	})
	$(".interest35").on("click",function(){
		$(this).css("background-color","tomato");
	});
	$(".interest35").click(function(){
		$(this).off("click");
	})
	$(".interest36").on("click",function(){
		$(this).css("background-color","tomato");
	});
	$(".interest36").click(function(){
		$(this).off("click");
	})
	$(".interest37").on("click",function(){
		$(this).css("background-color","tomato");
	});
	$(".interest37").click(function(){
		$(this).off("click");
	})
	$(".interest38").on("click",function(){
		$(this).css("background-color","tomato");
	});
	$(".interest38").click(function(){
		$(this).off("click");
	})
	$(".interest39").on("click",function(){
		$(this).css("background-color","tomato");
	});
	$(".interest39").click(function(){
		$(this).off("click");
	})
	$(".interest40").on("click",function(){
		$(this).css("background-color","tomato");
	});
	$(".interest40").click(function(){
		$(this).off("click");
	})
	$(".interest41").on("click",function(){
		$(this).css("background-color","tomato");
	});
	$(".interest41").click(function(){
		$(this).off("click");
	})
	$(".interest42").on("click",function(){
		$(this).css("background-color","tomato");
	});
	$(".interest42").click(function(){
		$(this).off("click");
	})
	$(".interest43").on("click",function(){
		$(this).css("background-color","tomato");
	});
	$(".interest43").click(function(){
		$(this).off("click");
	})
	$(".interest44").on("click",function(){
		$(this).css("background-color","tomato");
	});
	$(".interest44").click(function(){
		$(this).off("click");
	})
	$(".interest45").on("click",function(){
		$(this).css("background-color","tomato");
	});
	$(".interest45").click(function(){
		$(this).off("click");
	})
	$(".interest46").on("click",function(){
		$(this).css("background-color","tomato");
	});
	$(".interest46").click(function(){
		$(this).off("click");
	})
	$(".interest47").on("click",function(){
		$(this).css("background-color","tomato");
	});
	$(".interest47").click(function(){
		$(this).off("click");
	})
	$(".interest48").on("click",function(){
		$(this).css("background-color","tomato");
	});
	$(".interest48").click(function(){
		$(this).off("click");
	})
	$(".interest49").on("click",function(){
		$(this).css("background-color","tomato");
	});
	$(".interest49").click(function(){
		$(this).off("click");
	})
	$(".interest50").on("click",function(){
		$(this).css("background-color","tomato");
	});
	$(".interest50").click(function(){
		$(this).off("click");
	})
	$(".interest51").on("click",function(){
		$(this).css("background-color","tomato");
	});
	$(".interest51").click(function(){
		$(this).off("click");
	})
	$(".interest52").on("click",function(){
		$(this).css("background-color","tomato");
	});
	$(".interest52").click(function(){
		$(this).off("click");
	})
	$(".interest53").on("click",function(){
		$(this).css("background-color","tomato");
	});
	$(".interest53").click(function(){
		$(this).off("click");
	})
	$(".interest54").on("click",function(){
		$(this).css("background-color","tomato");
	});
	$(".interest54").click(function(){
		$(this).off("click");
	})
	$(".interest55").on("click",function(){
		$(this).css("background-color","tomato");
	});
	$(".interest55").click(function(){
		$(this).off("click");
	})
	$(".interest56").on("click",function(){
		$(this).css("background-color","tomato");
	});
	$(".interest56").click(function(){
		$(this).off("click");
	})
	$(".interest57").on("click",function(){
		$(this).css("background-color","tomato");
	});
	$(".interest57").click(function(){
		$(this).off("click");
	})
});
